CREATE SCHEMA IF NOT EXISTS KNOWLEDGE_BRAIN;
USE SCHEMA KNOWLEDGE_BRAIN;

CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECT_ID VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,
    CURRENT_DNA_ID VARCHAR(36),
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_PROJECTS PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS DOCUMENTS (
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    SOURCE_ID VARCHAR(4000) NOT NULL,
    FILENAME VARCHAR(1000) NOT NULL,
    DOCUMENT_FORMAT VARCHAR(32) NOT NULL,
    SHA256 VARCHAR(64) NOT NULL,
    SIZE_BYTES NUMBER(38, 0) NOT NULL,
    TITLE VARCHAR(2000),
    AUTHOR VARCHAR(1000),
    SUBJECT VARCHAR(2000),
    SOURCE_CREATED_AT TIMESTAMP_TZ,
    SOURCE_MODIFIED_AT TIMESTAMP_TZ,
    SECTION_COUNT NUMBER(38, 0) NOT NULL,
    CHARACTER_COUNT NUMBER(38, 0) NOT NULL,
    WORD_COUNT NUMBER(38, 0) NOT NULL,
    WARNINGS VARIANT NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_DOCUMENTS PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENTS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_SECTIONS (
    SECTION_ID VARCHAR(320) NOT NULL,
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    SEQUENCE NUMBER(38, 0) NOT NULL,
    SECTION_KIND VARCHAR(32) NOT NULL,
    TEXT VARCHAR NOT NULL,
    PAGE_NUMBER NUMBER(38, 0),
    SLIDE_NUMBER NUMBER(38, 0),
    HEADING VARCHAR(2000),
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_DOCUMENT_SECTIONS PRIMARY KEY (SECTION_ID),
    CONSTRAINT FK_SECTIONS_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(DOCUMENT_ID)
);

CREATE TABLE IF NOT EXISTS PROJECT_DNA (
    DNA_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    VERSION NUMBER(38, 0) NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    PROMPT_VERSION VARCHAR(100) NOT NULL,
    DNA_JSON VARIANT NOT NULL,
    GENERATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_PROJECT_DNA PRIMARY KEY (DNA_ID),
    CONSTRAINT FK_DNA_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_DNA_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(DOCUMENT_ID)
);

CREATE TABLE IF NOT EXISTS EMBEDDINGS (
    EMBEDDING_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    TARGET_TYPE VARCHAR(64) NOT NULL,
    TARGET_ID VARCHAR(320) NOT NULL,
    SECTION_SEQUENCE NUMBER(38, 0),
    CONTENT_SHA256 VARCHAR(64) NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    DIMENSIONS NUMBER(38, 0) NOT NULL,
    VECTOR VECTOR(FLOAT, 3072) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_EMBEDDINGS PRIMARY KEY (EMBEDDING_ID),
    CONSTRAINT FK_EMBEDDINGS_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(DOCUMENT_ID)
);

CREATE TABLE IF NOT EXISTS ENRICHMENT_RUNS (
    RUN_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    EMBEDDING_COUNT NUMBER(38, 0) NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_ENRICHMENT_RUNS PRIMARY KEY (RUN_ID)
);
