USE SCHEMA KNOWLEDGE_BRAIN;

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH_NODES (
    NODE_ID VARCHAR(36) NOT NULL,
    NODE_TYPE VARCHAR(64) NOT NULL,
    NORMALIZED_KEY VARCHAR(4000) NOT NULL,
    DISPLAY_NAME VARCHAR(4000) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_GRAPH_NODES PRIMARY KEY (NODE_ID),
    CONSTRAINT UQ_KNOWLEDGE_GRAPH_NODE_KEY UNIQUE (NODE_TYPE, NORMALIZED_KEY)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GRAPH_EDGES (
    EDGE_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DNA_ID VARCHAR(36) NOT NULL,
    SOURCE_NODE_ID VARCHAR(36) NOT NULL,
    TARGET_NODE_ID VARCHAR(36) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(64) NOT NULL,
    CLAIM_CONFIDENCE VARCHAR(16) NOT NULL,
    EVIDENCE VARIANT NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_GRAPH_EDGES PRIMARY KEY (EDGE_ID),
    CONSTRAINT FK_GRAPH_EDGE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_GRAPH_EDGE_DNA FOREIGN KEY (DNA_ID) REFERENCES PROJECT_DNA(DNA_ID),
    CONSTRAINT FK_GRAPH_EDGE_SOURCE FOREIGN KEY (SOURCE_NODE_ID)
        REFERENCES KNOWLEDGE_GRAPH_NODES(NODE_ID),
    CONSTRAINT FK_GRAPH_EDGE_TARGET FOREIGN KEY (TARGET_NODE_ID)
        REFERENCES KNOWLEDGE_GRAPH_NODES(NODE_ID)
);

CREATE TABLE IF NOT EXISTS GRAPH_PROJECTION_RUNS (
    PROJECTION_ID VARCHAR(36) NOT NULL,
    PROJECTION_VERSION NUMBER(38, 0) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DNA_ID VARCHAR(36) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    NODE_COUNT NUMBER(38, 0) NOT NULL,
    EDGE_COUNT NUMBER(38, 0) NOT NULL,
    PROJECTED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_GRAPH_PROJECTION_RUNS PRIMARY KEY (PROJECTION_ID),
    CONSTRAINT FK_GRAPH_RUN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_GRAPH_RUN_DNA FOREIGN KEY (DNA_ID) REFERENCES PROJECT_DNA(DNA_ID)
);

-- Clustering keys are intentionally deferred. Snowflake recommends them for very large,
-- selective workloads; representative production query and table-size measurements are
-- required before accepting their ongoing compute and storage cost.
