USE SCHEMA KNOWLEDGE_BRAIN;

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GAP_ASSESSMENTS (
    ASSESSMENT_ID VARCHAR(36) NOT NULL,
    POLICY_VERSION NUMBER(38, 0) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DNA_ID VARCHAR(36) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    GAP_COUNT NUMBER(38, 0) NOT NULL,
    DETECTED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_GAP_ASSESSMENTS PRIMARY KEY (ASSESSMENT_ID),
    CONSTRAINT FK_GAP_ASSESSMENT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_GAP_ASSESSMENT_DNA FOREIGN KEY (DNA_ID) REFERENCES PROJECT_DNA(DNA_ID)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_GAPS (
    GAP_ID VARCHAR(36) NOT NULL,
    ASSESSMENT_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DNA_ID VARCHAR(36) NOT NULL,
    FIELD_NAME VARCHAR(64) NOT NULL,
    GAP_KIND VARCHAR(32) NOT NULL,
    SEVERITY VARCHAR(32) NOT NULL,
    EXPLANATION VARCHAR(4000) NOT NULL,
    OBSERVED_VALUES VARIANT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    DETECTED_AT TIMESTAMP_TZ NOT NULL,
    RESOLVED_BY_FACT_ID VARCHAR(36),
    RESOLVED_AT TIMESTAMP_TZ,
    CONSTRAINT PK_KNOWLEDGE_GAPS PRIMARY KEY (GAP_ID),
    CONSTRAINT FK_KNOWLEDGE_GAP_ASSESSMENT FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES KNOWLEDGE_GAP_ASSESSMENTS(ASSESSMENT_ID),
    CONSTRAINT FK_KNOWLEDGE_GAP_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_KNOWLEDGE_GAP_DNA FOREIGN KEY (DNA_ID) REFERENCES PROJECT_DNA(DNA_ID)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_SUBMISSIONS (
    SUBMISSION_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    GAP_ID VARCHAR(36),
    FIELD_NAME VARCHAR(64) NOT NULL,
    PROPOSED_VALUE VARCHAR NOT NULL,
    RATIONALE VARCHAR(4000),
    SOURCE_REFERENCE VARCHAR(4000),
    SUBMITTER_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    VERSION NUMBER(38, 0) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_SUBMISSIONS PRIMARY KEY (SUBMISSION_ID),
    CONSTRAINT FK_KNOWLEDGE_SUBMISSION_PROJECT FOREIGN KEY (PROJECT_ID)
        REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_KNOWLEDGE_SUBMISSION_GAP FOREIGN KEY (GAP_ID) REFERENCES KNOWLEDGE_GAPS(GAP_ID)
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_APPROVAL_EVENTS (
    EVENT_ID VARCHAR(36) NOT NULL,
    SUBMISSION_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    ACTION VARCHAR(32) NOT NULL,
    ACTOR_ID VARCHAR(255) NOT NULL,
    FROM_STATUS VARCHAR(32),
    TO_STATUS VARCHAR(32) NOT NULL,
    REASON VARCHAR(4000),
    SUBMISSION_VERSION NUMBER(38, 0) NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_APPROVAL_EVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_APPROVAL_EVENT_SUBMISSION FOREIGN KEY (SUBMISSION_ID)
        REFERENCES KNOWLEDGE_SUBMISSIONS(SUBMISSION_ID),
    CONSTRAINT FK_APPROVAL_EVENT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS APPROVED_KNOWLEDGE (
    FACT_ID VARCHAR(36) NOT NULL,
    SUBMISSION_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    FIELD_NAME VARCHAR(64) NOT NULL,
    FACT_VALUE VARCHAR NOT NULL,
    SOURCE_REFERENCE VARCHAR(4000),
    APPROVED_BY VARCHAR(255) NOT NULL,
    APPROVED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_APPROVED_KNOWLEDGE PRIMARY KEY (FACT_ID),
    CONSTRAINT UQ_APPROVED_KNOWLEDGE_SUBMISSION UNIQUE (SUBMISSION_ID),
    CONSTRAINT FK_APPROVED_KNOWLEDGE_SUBMISSION FOREIGN KEY (SUBMISSION_ID)
        REFERENCES KNOWLEDGE_SUBMISSIONS(SUBMISSION_ID),
    CONSTRAINT FK_APPROVED_KNOWLEDGE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);

-- Approved knowledge is intentionally separate from generated Project DNA. A later
-- enrichment orchestration phase must explicitly incorporate facts, regenerate vectors,
-- and rebuild graph projections so unreviewed submissions can never enter retrieval.
