USE SCHEMA KNOWLEDGE_BRAIN;

CREATE TABLE IF NOT EXISTS PROPOSALS (
    ARTIFACT_ID VARCHAR(36) NOT NULL,
    REQUEST_ID VARCHAR(255) NOT NULL,
    SOURCE_PROJECT_IDS VARIANT NOT NULL,
    BRIEF VARIANT NOT NULL,
    TITLE VARCHAR(1000) NOT NULL,
    SUBTITLE VARCHAR(2000),
    CONTENT VARIANT NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    PROMPT_VERSION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CONTENT_SHA256 VARCHAR(64) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_PROPOSALS PRIMARY KEY (ARTIFACT_ID)
);

CREATE TABLE IF NOT EXISTS PROJECT_ONE_PAGERS (
    ARTIFACT_ID VARCHAR(36) NOT NULL,
    REQUEST_ID VARCHAR(255) NOT NULL,
    SOURCE_PROJECT_IDS VARIANT NOT NULL,
    BRIEF VARIANT NOT NULL,
    TITLE VARCHAR(1000) NOT NULL,
    SUBTITLE VARCHAR(2000),
    CONTENT VARIANT NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    PROMPT_VERSION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CONTENT_SHA256 VARCHAR(64) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_PROJECT_ONE_PAGERS PRIMARY KEY (ARTIFACT_ID)
);

CREATE TABLE IF NOT EXISTS ARTIFACT_CITATIONS (
    CITATION_ID VARCHAR(36) NOT NULL,
    ARTIFACT_ID VARCHAR(36) NOT NULL,
    ARTIFACT_KIND VARCHAR(32) NOT NULL,
    SECTION_KEY VARCHAR(100) NOT NULL,
    STATEMENT_SEQUENCE NUMBER(38, 0) NOT NULL,
    STATEMENT_TEXT VARCHAR(4000) NOT NULL,
    SOURCE_ID VARCHAR(32) NOT NULL,
    SOURCE_KIND VARCHAR(32) NOT NULL,
    PROJECT_ID VARCHAR(255),
    DOCUMENT_ID VARCHAR(36),
    SECTION_SEQUENCE NUMBER(38, 0),
    FILENAME VARCHAR(1000),
    QUOTE VARCHAR(500) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_ARTIFACT_CITATIONS PRIMARY KEY (CITATION_ID)
);

CREATE TABLE IF NOT EXISTS ARTIFACT_EXPORTS (
    EXPORT_ID VARCHAR(36) NOT NULL,
    ARTIFACT_ID VARCHAR(36) NOT NULL,
    ARTIFACT_KIND VARCHAR(32) NOT NULL,
    STORAGE_LOCATION VARCHAR(4000) NOT NULL,
    OBJECT_KEY VARCHAR(4000) NOT NULL,
    CONTENT_TYPE VARCHAR(255) NOT NULL,
    SIZE_BYTES NUMBER(38, 0) NOT NULL,
    SHA256 VARCHAR(64) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    CONSTRAINT PK_ARTIFACT_EXPORTS PRIMARY KEY (EXPORT_ID),
    CONSTRAINT UQ_ARTIFACT_EXPORT_OBJECT UNIQUE (STORAGE_LOCATION, OBJECT_KEY)
);

-- Artifacts remain explicitly draft status. Conditional foreign keys from the common
-- citation/export projections to two type-specific parent tables are not representable;
-- application transactions enforce the artifact-kind/identifier relationship.
